


# jwt.secret=7nd9ZcSrjsGla55Q9WiNO5gR5HX9qxu77nd9ZcSrjsGla55Q9WiNO5gR5HX9qxu7

server.port=8085

spring.application.name=HotelGateway
spring.eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Route Definitions:

# FrontOfficeService - GuestController (/api/v1/guests)
spring.cloud.gateway.routes[0].id=FrontOffice-Guests
spring.cloud.gateway.routes[0].uri=lb://bookingservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/frontOfficeService/v1/**
# spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# HotelMasterService - HotelController (/api/v1/hotels)
spring.cloud.gateway.routes[1].id=HotelMaster-Hotels
spring.cloud.gateway.routes[1].uri=lb://masterservice
# spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# HMS-Service Routes
spring.cloud.gateway.routes[2].id=HMS-Service-POS
spring.cloud.gateway.routes[2].uri=lb://hms-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/hmsService/v1/**
# spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

#HMS user service
spring.cloud.gateway.routes[13].id=User-Service-Audit
spring.cloud.gateway.routes[13].uri=lb://userservice
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/hmsUserService/v1/**
# spring.cloud.gateway.routes[13].filters[0]=AuthenticationFilter


# jwt.expirationDateInMin=1440
# jwt.refreshExpirationDateInMin=1540



spring.main.web-application-type= reactive
spring.main.allow-bean-definition-overriding=true

# Enable CORS globally for all endpoints
spring.web.cors.allow-origins=*
spring.web.cors.allow-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allow-headers=*
spring.web.cors.allow-credentials=true




# Set root log level
logging.level.root=INFO

# Set specific package log level
logging.level.org.springframework=INFO
logging.level.com.example=INFO
