server.port=9093

spring.application.name=HotelGateway

eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://adminserviceregistry:8761/eureka/

spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=true

# FrontOffice / Booking Service
spring.cloud.gateway.routes[0].id=FrontOffice-Guests
spring.cloud.gateway.routes[0].uri=lb://bookingservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/frontOfficeService/v1/**

# Master Service
spring.cloud.gateway.routes[1].id=HotelMaster-Hotels
spring.cloud.gateway.routes[1].uri=lb://masterservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/masterService/v1/**

# HMS Service
spring.cloud.gateway.routes[2].id=HMS-Service-POS
spring.cloud.gateway.routes[2].uri=lb://hmsservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/hmsService/v1/**

# User Service
spring.cloud.gateway.routes[3].id=User-Service-Audit
spring.cloud.gateway.routes[3].uri=lb://userservice
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/hmsUserService/v1/**

# Logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
